### ISSUE TITLE
Fix facter 2 incompatibilities

### ISSUE THREAD

**Issue by railsmachine-ops** [railsmachine/moonshine#190]
Facter 2 removed the `#method_missing` method [1] that allows you to use `Facter.fqdn` instead of `Facter.value(:fqdn)`. We rely on this functionality in several places throughout moonshine. In order to use facter 2 all of these instances will need to be updated to use the `#value` method.

[1] https://github.com/puppetlabs/facter/pull/623

**Comment by bryantraywick** [comment]
Fixed by #250
